spring.application.name=backend

# ==========================
# DATABASE CONFIGURATION
# ==========================

spring.datasource.url=jdbc:postgresql://localhost:5432/smarterp
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / HIBERNATE
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# SERVER
# ==========================

server.port=8080
app.jwt.secret=ZmY0NzQ0M2Y2MzY4NTk0OTY5NzA3ODUxNjY3MjY1NmU2MjQ5NjM2ZjY0Nzg2ODU2NzQ3MzY5NmQ0YzU5NTg2NjY4NTg3MjY0NjQ2ODQyNzQ2OTY5NjM2MjU5NTE=
app.jwt.expiration=86400000
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.default-produces-media-type=application/json